# Используем официальный Node.js образ
FROM node:18-alpine as build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальные файлы и собираем приложение
COPY . .
RUN npm run build

# Используем Nginx для сервинга статических файлов
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Копируем кастомный конфиг Nginx, если нужен (опционально)
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
